title: Project
files: true
pages: false
files:
  fields:
    caption:
      label: Caption
      type: textarea
    videolink:
      label: Video Link
      type: url
      help: Youtube or Vimeo
    videofile:
      label: Video File
      type: select
      options: videos
fields:
  prevnext: prevnext
  mainInfos:
    label: Main infos
    type: tabs
  title:
    label: Title
    type:  text
    width: 3/4
  featured:
    label: Featured image
    type: image
    help: Required to display project
    width: 1/4
  place:
    label: Place
    type:  text
    width: 1/4
    validate: 
      maxLength: 100
  projectcode:
    label: Code
    type: text
    required: true
    help: CHP, TRP...
    width: 1/4
  startdate:
    label: Start Date
    type:  date
    format: YYYY
    required: true
    width: 1/4
  enddate:
    label: End Date
    type:  date
    format: YYYY
    width: 1/4
  mission:
    label: Mission
    type: text
    width: 1/2
  client:
    label: Maîtrise d‘ouvrage
    type:  text
    width: 1/2
  surface:
    label: Surface
    type: text
    width: 1/2
  perimetre:
    label: Périmètre
    type: text
    width: 1/2
  programme:
    label: Programme
    type: text
    width: 1/2
  partenaires:
    label: Partenaires
    type: text
    width: 1/2
  tarifEtude:
    label: Montant de l’étude
    type: text
    width: 1/2
  tarifTravaux:
    label: Montant des travaux
    type: text
    width: 1/2
  additionalFields:
    label: Sections supplémentaires
    type: structure
    style: table
    fields:
      title:
        label: Title
        type: text
        required: true
      text:
        label: Text
        type: text
        required: true
  categories:
    label: Categories
    type: checkboxes
    options: field
    columns: 3
    field:
      page: ../
      name: categories
      separator: ,
  projectContent:
    label: Content
    type: tabs
  text:
    label: Description
    type: textarea
  medias: 
    label: Images
    type: images
  revisionsTabs:
    label: Revisions
    type: tabs
  revisions:
    label: Revisions
    type: revisions
